### PR TITLE
Fix to run under Mac OS X #73

### LINKED ISSUE #73: Ensure building and consuming boxes works across multiple OSes
- [ ] Document customizations required for host OSes
  - [ ] #72 #111
- [ ] Windows
  - [ ] 10
  - [ ] Server 2016
- [ ] Linux
- [ ] macOS

### PR DESCRIPTION
**Pull request by boustedo**
Adding ci.sh boostrapper to run it under Mac OS X and probably Linux.
Upgrade Cake to release 0.22.2 with latest addin.

Resolves #73.

### CODE REVIEW

**Comment by gusztavvargadr** [comment]
@boustedo thanks heaps for the contribution! I'll try to do some tests myself (though I have access only to Linux atm), and will get back to you.

**Comment by gusztavvargadr** [comment]
@boustedo thanks for the great analysis, sorry that I did not have the time yet to test it properly.

I can recall I had to fix the versions when 0.22.0 was released at https://github.com/gusztavvargadr/packer/commit/81536ddf3b4bd7741c7311b96809f4d04d4ea46a#diff-d1b4d7717b81225f983e4c6df57971ea as the dependencies got broken.

I would try the later versions of https://www.nuget.org/packages/Newtonsoft.Json/, maybe it's just an incorrect minimal version specification in `Cake.Json`. Btw, if we're not directly referencing `Newtonsoft.Json`, I would not add it as an explicit addin, as that's the responsibility of `Cake.Json`.

**Comment by boustedo** [comment]
@gusztavvargadr 
I make it work by running the Cake.CoreCLR dll with dotnet instead of using the Cake.exe binary. I also have to skip the verification. I don't understand why it work using "dotnet Cake.dll [...]". I will not investigate more for the moment. If you need me to test other stuff, let me know.

**Comment by gusztavvargadr** [comment]
@boustedo sorry that I never got to properly test and so merge this. I'm planning to move to the .NET Core tool model soon, so I'm closing this now.

https://cakebuild.net/blog/2018/08/cake-v0.30.0-released

Thanks again!

**Pull request closed without merging**
